version: '3.3'
services:
  # The Web Server
  web:
    env_file:
      - .env
    build: emilmoe/httpd
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
    user: local

  # The Database
  database:
    env_file:
      - .env
    build: emilmoe/sqld
    environment:
        - DATABASE=${DB_DATABASE}
    ports:
        - 3306:3306
