version: '3.3'
services:
  # The Web Server
  web:
    container_name: ${APP_NAME}
    env_file:
      - .env
    build: 
      context: https://github.com/EmilMoe/httpd.git
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
    user: local

  # The Database
  database:
    container_name: ${APP_NAME}_database
    env_file:
      - .env
    build: 
      context: https://github.com/EmilMoe/sqld.git
    environment:
        - DATABASE=${DB_DATABASE}
    ports:
        - 3306:3306
