#!/bin/bash

NAME=$(echo ${PWD##*/} | tr '[:upper:]' '[:lower:]')

if [ $# -eq 0 ]
  then
    echo "Options are:"
    echo "artisan"
    echo "build"
    echo "start"
    echo "stop"
    echo "phpunit"
    echo "exec"
    echo "npm"
    echo "self-update"
    echo "composer"
fi

if [[ $1 = "artisan" ]] ; then
    docker exec ${NAME}_web_1 php artisan "${@:2}"
fi

if [[ $1 = "build" ]] ; then
    read -p "This will rebuild and overwriting any existing containers for this project. Are you sure? " -n 1 -r
    echo    # (optional) move to a new line
    if [[ $REPLY =~ ^[Yy]$ ]] ; then
        curl https://raw.githubusercontent.com/EmilMoe/vm/master/docker-compose.yml > docker-compose.yml
        docker-compose up --build -d

        ./vm composer -n install
        ./vm artisan key:generate
        ./vm npm install --no-optional
        ./vm php artisan migrate --seed
        ./vm npm run dev
    fi
fi

if [[ $1 = "start" ]] ; then
    docker container start ${NAME}_database_1
    docker container start ${NAME}_web_1
fi

if [[ $1 = "stop" ]] ; then
    docker container stop ${NAME}_database_1
    docker container stop ${NAME}_web_1
fi

if [[ $1 = "phpunit" ]] ; then
    docker exec ${NAME}_web_1 vendor/phpunit/phpunit/phpunit "${@:2}"
fi

if [[ $1 = "exec" ]] ; then
    docker exec ${NAME}_web_1 "${@:2}"
fi

if [[ $1 = "npm" ]] ; then
    docker exec ${NAME}_web_1 npm "${@:2}"
fi

if [[ $1 = "composer" ]] ; then
    docker exec ${NAME}_web_1 composer "${@:2}"
fi

if [[ $1 = "self-update" ]] ; then
    curl -s https://raw.githubusercontent.com/EmilMoe/vm/master/vm > vm
    echo "Updated"
fi
